name: deluxe_bottom_bar
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

# The following section is specific to Flutter packages.
flutter: null
# Bu alana asset eklemek istiyorsanız aşağıdaki gibi düzenleyebilirsiniz:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
